{% set name = "signalslot" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64da1d89b3467c239af317779b237e7116b6f2b637ff29cd5226b59308d320e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - contexter
    - eventlet
    - six
    - weakrefmethod

test:
  imports:
    - signalslot
    - signalslot.contrib
    - signalslot.contrib.task

about:
  home: https://github.com/numergy/signalslot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple Signal/Slot implementation

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
